### ISSUE TITLE
Evaluating python code from Wolfram Language

### ISSUE THREAD

**Issue by arnoudbuzing** [statius/Minuit#1]
This is more a question than an issue, but version 12.0 has `StartExternalSession` and `ExternalEvaluate` built-in for Python. Did this not meet your needs?

**Comment by arnoudbuzing** [comment]
For example:

![image](https://user-images.githubusercontent.com/3236874/65546359-fcfb2680-dedc-11e9-8467-1cd4a7e912f8.png)

**Comment by statius** [comment]
The new external language functionality is exactly what got me started on this (and is what is used internally by the package). Unfortunately, it alone does not allow direct manipulation of the data objects constructed by _iminuit_ (only of whatever data can be translated into the Wolfram Language). To work with them, everything has to be mediated by `ExternalEvaluate` and coded in Python (which is currently still a little awkward, given that all commands must be encoded as strings and there is no syntax highlighting, etc.). This package is simply a wrapper to automate this process and hopefully enable more natural and modular Wolfram Language code.

**Comment by arnoudbuzing** [comment]
Very interesting, thank you for the feedback. I work at Wolfram Research and am involved in the `ExternalEvaluate` project, so I have a stake in improving this functionality (for you and all users).

**Comment by statius** [comment]
For what it is worth, I think `ExternalEvaluate` and friends are very positive additions to the Wolfram Language. They make this kind of interface an order of magnitude easier to construct, opening up a lot of new territory.
